let cardProp = [
    {
      prod_img: "images/product9.png",
      prod_name: "Breed Dry Dog Food",
      prod_price: "$100",
      prod_cutPrice: " ",
      prod_reviews: "(35)",
      prod_rating: "images/threestar.png",
      showDiscountTag: false,
    },
    {
      prod_img: "images/product10.png",
      prod_name: "CANON EOS DSLR Camera",
      prod_price: "$360",
      prod_cutPrice: " ",
      prod_reviews: "(95)",
      prod_rating: "images/fourstar.png",
      showDiscountTag: false,
    },
    {
      prod_img: "images/product11.png",
      prod_name: "ASUS FHD Gaming Laptop",
      prod_price: "$700",
      prod_cutPrice: " ",
      prod_reviews: "(325)",
      prod_rating: "images/fivestar.png",
      showDiscountTag: false,
    },
    {
      prod_img: "images/product12.png",
      prod_name: "Curology Product Set ",
      prod_price: "$500",
      prod_cutPrice: " ",
      prod_reviews: "(145)",
      prod_rating: "images/fourstar.png",
      className: "w-full",
      showDiscountTag: false,
    },
    {
      prod_img: "images/product13.png",
      prod_name: "Kids Electric Car",
      prod_discount: "New",
      prod_price: "$960",
      prod_reviews: "(65)",
      prod_cutPrice: " ",
      prod_rating: "images/fivestar.png",
    },
    {
      prod_img: "images/product14.png",
      prod_name: "Jr. Zoom Soccer Cleats",
      prod_price: "$1160",
      prod_cutPrice: " ",
      prod_reviews: "(35)",
      prod_rating: "images/fivestar.png",
      showDiscountTag: false,
    },
    {
      prod_img: "images/product15.png",
      prod_name: "GP11 Shooter USB Gamepad",
      prod_discount: "New",
      prod_cutPrice: " ",
      prod_price: "$660",
      prod_reviews: "(65)",
      prod_rating: "images/fourhalfstar.png",
    },
    {
      prod_img: "images/product16.png",
      prod_name: "Quilted Satin Jacket",
      prod_price: "$660",
      prod_cutPrice: " ",
      prod_reviews: "(55)",
      prod_rating: "images/fourhalfstar.png",
      showDiscountTag: false,
    }
  ];

  export default cardProp;