let cardProp = [
    {
        prod_img: "images/product1.png",
        prod_name: "HAVIT HV-G92 Gamepad",
        prod_discount: "-40%",
        prod_price: "$120",
        prod_cutPrice: "$160",
        prod_reviews: "(88)",
        prod_rating: "images/fivestar.png",
    },
    {
        prod_img: "images/product2.png",
        prod_name: "AK-900 Wired Keyboard",
        prod_discount: "-35%",
        prod_price: "$960",
        prod_cutPrice: "$1160",
        prod_reviews: "(75)",
        prod_rating: "images/fourstar.png",
    },
    {
        prod_img: "images/product3.png",
        prod_name: "IPS LCD Gaming Monitor",
        prod_discount: "-30%",
        prod_price: "$370",
        prod_cutPrice: "$400",
        prod_reviews: "(99)",
        prod_rating: "images/fivestar.png",
    },
    {
        prod_img: "images/product4.png",
        prod_name: "S-Series Comfort Chair",
        prod_discount: "-25%",
        prod_price: "$375",
        prod_cutPrice: "$400",
        prod_reviews: "(99)",
        prod_rating: "images/fourhalfstar.png",
        className: "w-full",
    },
    {
        prod_img: "images/product3.png",
        prod_name: "IPS LCD Gaming Monitor",
        prod_discount: "-30%",
        prod_price: "$370",
        prod_cutPrice: "$400",
        prod_reviews: "(99)",
        prod_rating: "images/fivestar.png",
    },
    {
        prod_img: "images/product1.png",
        prod_name: "HAVIT HV-G92 Gamepad",
        prod_discount: "-40%",
        prod_price: "$120",
        prod_cutPrice: "$160",
        prod_reviews: "(88)",
        prod_rating: "images/fivestar.png",
    },
];

export default cardProp;